#ifndef WEB_CONTENT_H
#define WEB_CONTENT_H

static const char index_html[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "    <meta charset=\"utf-8\">\n"
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "    <title>Badge Text Editor</title>\n"
    "    <style>\n"
    "        body { margin: 0; padding: 0; background-color: #4449db; font-family: Arial, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; }\n"
    "        .container { background-color: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.2); text-align: center; width: 90%; max-width: 400px; }\n"
    "        h1 { margin-bottom: 20px; }\n"
    "        input[type=\"text\"] { width: 80%; padding: 10px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 4px; font-size: 16px; }\n"
    "        button { padding: 10px 20px; background-color: #4449db; border: none; border-radius: 4px; color: #fff; font-size: 16px; cursor: pointer; }\n"
    "        button:hover { background-color: #0056b3; }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "    <div class=\"container\">\n"
    "        <h1>Badge Text Editor</h1>\n"
    "        <form id=\"textForm\">\n"
    "            <input type=\"text\" id=\"first_name\" placeholder=\"First Name\">\n"
    "            <input type=\"text\" id=\"last_name\" placeholder=\"Last Name\">\n"
    "            <input type=\"text\" id=\"additional_info\" placeholder=\"Additional Info\">\n"
    "            <button type=\"submit\">Send</button>\n"
    "        </form>\n"
    "    </div>\n"
    "    <script>\n"
    "        document.getElementById('textForm').addEventListener('submit', async (e) => {\n"
    "            e.preventDefault();\n"
    "            const data = {\n"
    "                first_name: document.getElementById('first_name').value,\n"
    "                last_name: document.getElementById('last_name').value,\n"
    "                additional_info: document.getElementById('additional_info').value\n"
    "            };\n"
    "            const response = await fetch('/sendtext', {\n"
    "                method: 'POST',\n"
    "                headers: { 'Content-Type': 'application/json' },\n"
    "                body: JSON.stringify(data)\n"
    "            });\n"
    "            if (response.ok) {\n"
    "                const result = await response.json();\n"
    "                console.log(JSON.stringify(result, null, 2));\n"
    "                showSuccessPopup();\n"
    "            } else {\n"
    "                console.error('Response not OK:', response.statusText);\n"
    "            }\n"
    "        });\n"
    "\n"
    "        function showSuccessPopup() {\n"
    "            const popup = document.createElement('div');\n"
    "            popup.innerHTML = '&#x2705;';\n"
    "            popup.style.position = 'fixed';\n"
    "            popup.style.top = '20px';\n"
    "            popup.style.right = '20px';\n"
    "            popup.style.backgroundColor = '#d4edda';\n"
    "            popup.style.color = '#155724';\n"
    "            popup.style.padding = '10px 15px';\n"
    "            popup.style.borderRadius = '5px';\n"
    "            popup.style.boxShadow = '0 2px 6px rgba(0,0,0,0.2)';\n"
    "            popup.style.fontSize = '24px';\n"
    "            popup.style.zIndex = '9999';\n"
    "            document.body.appendChild(popup);\n"
    "            setTimeout(() => { popup.remove(); }, 2000);\n"
    "        }\n"
    "    </script>\n"
    "</body>\n"
    "</html>\n";

#endif // WEB_CONTENT_H
